### PR TITLE
Freqdisp

### PR DESCRIPTION
**Pull request by Ecobbold**
Added Time signature, ledger support, and drawing bars.

Also minor changes to x/y magic/math.

---
This change is [Reviewable](https://reviewable.io/reviews/uiri/trebletrouble/66)

### CODE REVIEW

**Comment by uiri** [comment]
Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 24 at r1](https://reviewable.io:443/reviews/uiri/trebletrouble/66#-KXreNjzzs1zoPQYf5Jb:-KXreNk-r-T_bOdoiy1w:bjik8fb) ([raw file](https://github.com/uiri/trebletrouble/blob/51f677bfa8eba269c2fd2d1acf5a0db6d445101b/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L24)):*
> ```C
> char *OCTAVE[9] = {"/srv/trebletrouble/0.pnm", "/srv/trebletrouble/1.pnm", "/srv/trebletrouble/2.pnm", "/srv/trebletrouble/3.pnm", "/srv/trebletrouble/4.pnm", "/srv/trebletrouble/5.pnm", "/srv/trebletrouble/6.pnm", "/srv/trebletrouble/7.pnm", "/srv/trebletrouble/8.pnm"};
> 
> char *TIME_STAMP[8] = {"","/srv/trebletrouble/2_ts.pnm","/srv/trebletrouble/3_ts.pnm","/srv/trebletrouble/4_ts.pnm","/srv/trebletrouble/5_ts.pnm","","/srv/trebletrouble/7_ts.pnm","/srv/trebletrouble/8_ts.pnm"};
> ```

so TIMESTAMP[i] will place i ?
shouldn't it be TIMESTAMP[10] and go from 0 to 9? In which case you're missing 0 at the start and 9 at the end. If you do follow this, you'll need to change `time_signature` and remove the `-1`s

nit: Empty strings are fine, NULL pointers would be better.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 67 at r1](https://reviewable.io:443/reviews/uiri/trebletrouble/66#-KXrenXoTsQ96K5Z2GJv:-KXrenXpc_X-NzKsb9fc:b9ss8zv) ([raw file](https://github.com/uiri/trebletrouble/blob/51f677bfa8eba269c2fd2d1acf5a0db6d445101b/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L67)):*
> ```C
> }
> 
> void draw_note(int i, int ynote, char* fbp, short colour, int time) {
> ```

oh cool

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 77 at r1](https://reviewable.io:443/reviews/uiri/trebletrouble/66#-KXrf-6HAdMEqnD2p0oj:-KXrf-6Iot8ygU-I8R0_:b870xdz) ([raw file](https://github.com/uiri/trebletrouble/blob/51f677bfa8eba269c2fd2d1acf5a0db6d445101b/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L77)):*
> ```C
> 	if(ynote > 239){
> 		bitblit(L_PIC, fbp, get_xnote(i)-3, 225);
> 	}
> ```

Will this need to be refactored when we add more notes or the bass clef?
It might make sense to move it into its own function now while it is small rather than later when it gets larger.
Or create a macro to parameterize the code copy-pasta:

```
#define DRAW_LEDGER(COND, Y) if (COND) { \
        bitblit(L_PIC, fbp, get_xnote(i)-3, Y); \
}
```

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 106 at r1](https://reviewable.io:443/reviews/uiri/trebletrouble/66#-KXrglfpX5O3JW9nbMJK:-KXrglfpX5O3JW9nbMJL:b-n4qaqj) ([raw file](https://github.com/uiri/trebletrouble/blob/51f677bfa8eba269c2fd2d1acf5a0db6d445101b/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L106)):*
> ```C
> 	/*hard coding bar spaces for now
> 	with xstart being defined in display.h, and there's 4 notes per bar
> 	each bar will be 160 apart*/
> ```

We'll need to add logic for detecting how many notes per bar... oh jeez

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 233 at r1](https://reviewable.io:443/reviews/uiri/trebletrouble/66#-KXrgzhUIrrjJpeLWekZ:-KXrgzhUIrrjJpeLWek_:b-7s3rgo) ([raw file](https://github.com/uiri/trebletrouble/blob/51f677bfa8eba269c2fd2d1acf5a0db6d445101b/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L233)):*
> ```C
> 
> 	/*draw bars on staff*/
> 	draw_bar(fbp);
> ```

Shouldn't this go in `load_song` since the bars are based on the time signature?

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 286 at r1](https://reviewable.io:443/reviews/uiri/trebletrouble/66#-KXrhbsSfb_P79JLCZkA:-KXrhbsSfb_P79JLCZkB:b8bqqdz) ([raw file](https://github.com/uiri/trebletrouble/blob/51f677bfa8eba269c2fd2d1acf5a0db6d445101b/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L286)):*
> ```C
> void load_song(FILE *song, char *fbp, int expected[NUM_NOTES]) {
> 	unsigned char buf[2];
> ```

nit: whitespace

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.h, line 11 at r1](https://reviewable.io:443/reviews/uiri/trebletrouble/66#-KXrhPiUGxSA41SuzTrO:-KXrhPiVXLd6d646svAK:bn41x8t) ([raw file](https://github.com/uiri/trebletrouble/blob/51f677bfa8eba269c2fd2d1acf5a0db6d445101b/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.h#L11)):*
> ```objc
> Q_N - quater note
> W_N - whole note
> _F is flipped */
> ```

So W_N doesn't need a flip... Will half notes and eighth notes?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/uiri/trebletrouble/66)*

**Comment by Ecobbold** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 24 at r1](https://reviewable.io:443/reviews/uiri/trebletrouble/66#-KXreNjzzs1zoPQYf5Jb:-KXs4Q2p1q76nztpGxab:bba4az4) ([raw file](https://github.com/uiri/trebletrouble/blob/51f677bfa8eba269c2fd2d1acf5a0db6d445101b/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L24)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

so TIMESTAMP[i] will place i ?
shouldn't it be TIMESTAMP[10] and go from 0 to 9? In which case you're missing 0 at the start and 9 at the end. If you do follow this, you'll need to change `time_signature` and remove the `-1`s

nit: Empty strings are fine, NULL pointers would be better.
</blockquote></details>

The idea is that given, for example, 4,4, it places 4,4. 

And we're really only dealing with 4,4 now, and I added the others for later... I guess I'll need to add 6. For now we're not dealing with any 0 or 9 times... 
https://en.wikipedia.org/wiki/Time_signature#Most_frequent_time_signatures

I guess to be complete I could add error handling if the numbers given are out of bounds.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 67 at r1](https://reviewable.io:443/reviews/uiri/trebletrouble/66#-KXrenXoTsQ96K5Z2GJv:-KXs5nHKjhDjobAwAtiD:bo44h6m) ([raw file](https://github.com/uiri/trebletrouble/blob/51f677bfa8eba269c2fd2d1acf5a0db6d445101b/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L67)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

oh cool
</blockquote></details>

This is the first thoughts about time management for the notes.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 77 at r1](https://reviewable.io:443/reviews/uiri/trebletrouble/66#-KXrf-6HAdMEqnD2p0oj:-KXs6mvFcDW1Xxb4QGOV:bv6qoj1) ([raw file](https://github.com/uiri/trebletrouble/blob/51f677bfa8eba269c2fd2d1acf5a0db6d445101b/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L77)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

Will this need to be refactored when we add more notes or the bass clef?
It might make sense to move it into its own function now while it is small rather than later when it gets larger.
Or create a macro to parameterize the code copy-pasta:

```
#define DRAW_LEDGER(COND, Y) if (COND) { \
        bitblit(L_PIC, fbp, get_xnote(i)-3, Y); \
}
```

</blockquote></details>

It shouldn't since how we planned it out, to fit the bass clef, we won't have to move the treble clef. 
This can be added to a "clean-up" if we get a chance after exams.. for now it's fine.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 233 at r1](https://reviewable.io:443/reviews/uiri/trebletrouble/66#-KXrgzhUIrrjJpeLWekZ:-KXs7IBJuBEdWgpCGrwm:b4ylmil) ([raw file](https://github.com/uiri/trebletrouble/blob/51f677bfa8eba269c2fd2d1acf5a0db6d445101b/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L233)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

Shouldn't this go in `load_song` since the bars are based on the time signature?
</blockquote></details>

For now, the bars are being drawn with the staff, and then you draw the notes on it. Each bar is the same length etc etc.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.h, line 11 at r1](https://reviewable.io:443/reviews/uiri/trebletrouble/66#-KXrhPiUGxSA41SuzTrO:-KXs7mtVoGz9KQncs5kd:bkmux2e) ([raw file](https://github.com/uiri/trebletrouble/blob/51f677bfa8eba269c2fd2d1acf5a0db6d445101b/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.h#L11)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

So W_N doesn't need a flip... Will half notes and eighth notes?
</blockquote></details>

whole notes are whole. You're maybe thinking doubles?

I added this image to replace the NOTE_PIC but ended up not using it, but keeping it as an option, for use if we want to play with note duration. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/uiri/trebletrouble/66)*

**Comment by Ecobbold** [comment]
*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 24 at r1](https://reviewable.io:443/reviews/uiri/trebletrouble/66#-KXreNjzzs1zoPQYf5Jb:-KXsBwiNJEBHULzc8vp9:bnwjsiz) ([raw file](https://github.com/uiri/trebletrouble/blob/51f677bfa8eba269c2fd2d1acf5a0db6d445101b/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L24)):*
<details><summary><i>Previously, Ecobbold (Emilie Cobbold) wrote…</i></summary><blockquote>

The idea is that given, for example, 4,4, it places 4,4. 

And we're really only dealing with 4,4 now, and I added the others for later... I guess I'll need to add 6. For now we're not dealing with any 0 or 9 times... 
https://en.wikipedia.org/wiki/Time_signature#Most_frequent_time_signatures

I guess to be complete I could add error handling if the numbers given are out of bounds.


</blockquote></details>

Follow up:
Fixed TIMESTAMP and took the -1s

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/uiri/trebletrouble/66)*

**Comment by Ecobbold** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 233 at r1](https://reviewable.io:443/reviews/uiri/trebletrouble/66#-KXrgzhUIrrjJpeLWekZ:-KXsESo_xizQttFSMyij:b-jeuaad) ([raw file](https://github.com/uiri/trebletrouble/blob/51f677bfa8eba269c2fd2d1acf5a0db6d445101b/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L233)):*
<details><summary><i>Previously, Ecobbold (Emilie Cobbold) wrote…</i></summary><blockquote>

For now, the bars are being drawn with the staff, and then you draw the notes on it. Each bar is the same length etc etc.
</blockquote></details>

follow up:
Moved to load_song

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/uiri/trebletrouble/66)*

**Comment by uiri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 24 at r1](https://reviewable.io:443/reviews/uiri/trebletrouble/66#-KXreNjzzs1zoPQYf5Jb:-KXsEB--kXeEibWPavgV:bmxilld) ([raw file](https://github.com/uiri/trebletrouble/blob/51f677bfa8eba269c2fd2d1acf5a0db6d445101b/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L24)):*
<details><summary><i>Previously, Ecobbold (Emilie Cobbold) wrote…</i></summary><blockquote>

Follow up:
Fixed TIMESTAMP and took the -1s
</blockquote></details>

:LGTM:

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 77 at r1](https://reviewable.io:443/reviews/uiri/trebletrouble/66#-KXrf-6HAdMEqnD2p0oj:-KXsBaq0IBdKMw3PfgGN:bcnvf8) ([raw file](https://github.com/uiri/trebletrouble/blob/51f677bfa8eba269c2fd2d1acf5a0db6d445101b/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L77)):*
<details><summary><i>Previously, Ecobbold (Emilie Cobbold) wrote…</i></summary><blockquote>

It shouldn't since how we planned it out, to fit the bass clef, we won't have to move the treble clef. 
This can be added to a "clean-up" if we get a chance after exams.. for now it's fine.
</blockquote></details>

Hmm, OK. I figure we'll need more ledgers when we add the bass clef but this is fine.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 233 at r1](https://reviewable.io:443/reviews/uiri/trebletrouble/66#-KXrgzhUIrrjJpeLWekZ:-KXsC8lPObDBjmtQY-1R:bb6ywmx) ([raw file](https://github.com/uiri/trebletrouble/blob/51f677bfa8eba269c2fd2d1acf5a0db6d445101b/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L233)):*
<details><summary><i>Previously, Ecobbold (Emilie Cobbold) wrote…</i></summary><blockquote>

follow up:
Moved to load_song
</blockquote></details>

LGTM

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.h, line 11 at r1](https://reviewable.io:443/reviews/uiri/trebletrouble/66#-KXrhPiUGxSA41SuzTrO:-KXsBqAyiv_oDE2m1HBA:bdfovc7) ([raw file](https://github.com/uiri/trebletrouble/blob/51f677bfa8eba269c2fd2d1acf5a0db6d445101b/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.h#L11)):*
<details><summary><i>Previously, Ecobbold (Emilie Cobbold) wrote…</i></summary><blockquote>

whole notes are whole. You're maybe thinking doubles?

I added this image to replace the NOTE_PIC but ended up not using it, but keeping it as an option, for use if we want to play with note duration. 
</blockquote></details>

I think I've derped a bit.
Whole notes and half notes use the outlined notehead; quarter, eighth, etc. notes use the filled in notehead.
So when we add half notes later, we'll need the flipped W_N but not yet.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/uiri/trebletrouble/66#-:-KXsFX0ODRDBxG50oVJX:bnfp4nl)*

**Pull request merged**
