### PR TITLE
Freqdisp

### PR DESCRIPTION
**Pull request by Ecobbold**
Display_test includes a way to capture fbp to create a pnm file for easy testing on our VM.

Display_test tests the code to draw staff and notes onto the board, in the hopes to be later added to app.c

---
This change is [Reviewable](https://reviewable.io/reviews/uiri/trebletrouble/61)

### CODE REVIEW

**Comment by uiri** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[Makefile, line 35 at r1](https://reviewable.io:443/reviews/uiri/trebletrouble/61#-KXkhl25sO2vkQ5C3hqb:-KXkhl28zJDr2bTPLRgr:bga2jdx) ([raw file](https://github.com/uiri/trebletrouble/blob/983252c95038e571d81a02f9e766ecfd3efce126/Makefile#L35)):*
> ```Makefile
> 	$(CC) $(CFLAGS) $^ -o $@
> ```

FYI could you remove the extra whitespace in this file?

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/app.c, line 24 at r1](https://reviewable.io:443/reviews/uiri/trebletrouble/61#-KXkiGDgeZrDVa-1WBoM:-KXkiGDi-BiAPYUiPdud:bxovpg) ([raw file](https://github.com/uiri/trebletrouble/blob/983252c95038e571d81a02f9e766ecfd3efce126/bbb/meta-bbb/recipes-core/trebletrouble/files/src/app.c#L24)):*
> ```C
> 
> 	sleep(5);
> 	colour_screen(hbp, WHITE);
> ```

lol typo `hbp` doesn't compile. Did you mean `fbp`

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/app.c, line 33 at r1](https://reviewable.io:443/reviews/uiri/trebletrouble/61#-KXkiQPAMfD8lAhReFbE:-KXkiQPAMfD8lAhReFbF:bk8139l) ([raw file](https://github.com/uiri/trebletrouble/blob/983252c95038e571d81a02f9e766ecfd3efce126/bbb/meta-bbb/recipes-core/trebletrouble/files/src/app.c#L33)):*
> ```C
> 	//sleep(10);
> 	//display_frequency(28.0, fbp);
> 	//sleep(10);
> ```

:question: TODO: Add useful display code

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 131 at r1](https://reviewable.io:443/reviews/uiri/trebletrouble/61#-KXkiulrwfLREzbPeLwZ:-KXkiulu47ghdBzY3qEl:b4jhxuc) ([raw file](https://github.com/uiri/trebletrouble/blob/983252c95038e571d81a02f9e766ecfd3efce126/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L131)):*
> ```C
> 	vw = (x+w) > 800 ? x+w-799 : 0;
> 
> 	
> ```

FYI: clean up whitespace

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display_test.c, line 17 at r1](https://reviewable.io:443/reviews/uiri/trebletrouble/61#-KXkjg_4h8AsgXCqExMi:-KXkjg_5lIaIiyebZRZW:brkk79l) ([raw file](https://github.com/uiri/trebletrouble/blob/983252c95038e571d81a02f9e766ecfd3efce126/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display_test.c#L17)):*
> ```C
> char *NOTE_PIC = "/srv/trebletrouble/note.pnm";
> char *L_PIC = "/srv/trebletrouble/note_l.pnm";
> char *SONG = "/srv/trebletrouble/testnotes"; 
> ```

These should probably be `#define`'d as macros

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display_test.c, line 25 at r1](https://reviewable.io:443/reviews/uiri/trebletrouble/61#-KXkjvsJpl8hxeuwEXua:-KXkjvsMHxcvcDtj72YM:b-fxkxij) ([raw file](https://github.com/uiri/trebletrouble/blob/983252c95038e571d81a02f9e766ecfd3efce126/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display_test.c#L25)):*
> ```C
> 	char* e = fbp+800*480*2;
> 	
> 	//creating buf for r -> buf[0], g -> buf[1] & buf[2], b -> buf[3]
> ```

buf[3] only has 3 bytes... did you mean g -> buf[1], b -> buf[2] or did you mean to make buf 4 bytes wide?

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display_test.c, line 32 at r1](https://reviewable.io:443/reviews/uiri/trebletrouble/61#-KXkkmAS6Tifd9xsuNFZ:-KXkkmAUyNdofqJoOWv9:b-r0bq6b) ([raw file](https://github.com/uiri/trebletrouble/blob/983252c95038e571d81a02f9e766ecfd3efce126/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display_test.c#L32)):*
> ```C
> 	fwrite("P6\n800 480\n255\n",1, 15, file); 
> 	
> 	if (file == NULL){
> ```

This check should occur before you use `file`. As the code is written, the compiler will optimize this check away.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display_test.c, line 46 at r1](https://reviewable.io:443/reviews/uiri/trebletrouble/61#-KXkl1m9SrIBO3Bd7C0Q:-KXkl1mC9Yna8yXd4ole:bkoouub) ([raw file](https://github.com/uiri/trebletrouble/blob/983252c95038e571d81a02f9e766ecfd3efce126/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display_test.c#L46)):*
> ```C
> 		//check nonblack pixels because black pixels are scary
> 		/*if(px[0] || px[1])
> 			printf("NonBlack pixel\n");*/
> ```

Please take out the debug code

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display_test.c, line 63 at r1](https://reviewable.io:443/reviews/uiri/trebletrouble/61#-KXklh9xcSHx0gKS1-DJ:-KXklh9yROr1u_g8qakp:bdym6pd) ([raw file](https://github.com/uiri/trebletrouble/blob/983252c95038e571d81a02f9e766ecfd3efce126/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display_test.c#L63)):*
> ```C
> void draw_note(unsigned char *buf, int xnote, char* fbp){
> 	int ynote;
> 	printf("buf:%s\n", buf);
> ```

Should this debug print statement be removed?

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display_test.c, line 66 at r1](https://reviewable.io:443/reviews/uiri/trebletrouble/61#-KXkm4PAE846hT_7loHB:-KXkm4PAE846hT_7loHC:b5m7kko) ([raw file](https://github.com/uiri/trebletrouble/blob/983252c95038e571d81a02f9e766ecfd3efce126/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display_test.c#L66)):*
> ```C
> 	/*Middle C = 240*/
> 	/* find the y position for each note*/
> 	ynote =(240 - (((buf[1]-'4') * 105) + (((buf[0]-'C'+7)%7)*15)));
> ```

BTW you might want to add a comment to explain 105 (distance between same note in different octaves) and 15 ( distance between different notes)

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display_test.c, line 109 at r1](https://reviewable.io:443/reviews/uiri/trebletrouble/61#-KXknJrBh6ktdhEQ2apA:-KXknJrCWVCB32d_wxT2:b6k8x77) ([raw file](https://github.com/uiri/trebletrouble/blob/983252c95038e571d81a02f9e766ecfd3efce126/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display_test.c#L109)):*
> ```C
> 
> 	//draw the lines of the staff	
> 	for(i=0; i < 5; i++){
> ```

FYI: neat trick you can do `for (i = 0; i < 5; i++, y += m)` 

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display_test.c, line 115 at r1](https://reviewable.io:443/reviews/uiri/trebletrouble/61#-KXknpYUWT8QIDq8Tu3l:-KXknpYWGVP9ecux0Mzy:b-l1wgp9) ([raw file](https://github.com/uiri/trebletrouble/blob/983252c95038e571d81a02f9e766ecfd3efce126/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display_test.c#L115)):*
> ```C
> 	
> 		
> 	//for testing: place notes on the board from a song
> ```

This should end up in `display.c` so we can load a song onto the display on the board, no?

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display_test.c, line 124 at r1](https://reviewable.io:443/reviews/uiri/trebletrouble/61#-KXkmqIhF6HAM22CEm36:-KXkmqIisJELxCrt9Day:b-2curom) ([raw file](https://github.com/uiri/trebletrouble/blob/983252c95038e571d81a02f9e766ecfd3efce126/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display_test.c#L124)):*
> ```C
> 	fclose(song);
> 
> 	//writes the thing to a pnm hopefully
> ```

You don't need to hope. You can test the software.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/uiri/trebletrouble/61)*

**Comment by Ecobbold** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[Makefile, line 35 at r1](https://reviewable.io:443/reviews/uiri/trebletrouble/61#-KXkhl25sO2vkQ5C3hqb:-KXkt8Upx3ksk7HxCLCA:b-oy5ixl) ([raw file](https://github.com/uiri/trebletrouble/blob/983252c95038e571d81a02f9e766ecfd3efce126/Makefile#L35)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

FYI could you remove the extra whitespace in this file?
</blockquote></details>



Done.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display_test.c, line 32 at r1](https://reviewable.io:443/reviews/uiri/trebletrouble/61#-KXkkmAS6Tifd9xsuNFZ:-KXl2uljLLdyzPjipPw_:b-896fix) ([raw file](https://github.com/uiri/trebletrouble/blob/983252c95038e571d81a02f9e766ecfd3efce126/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display_test.c#L32)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

This check should occur before you use `file`. As the code is written, the compiler will optimize this check away.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/uiri/trebletrouble/61)*

**Comment by Ecobbold** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[Makefile, line 35 at r1](https://reviewable.io:443/reviews/uiri/trebletrouble/61#-KXkhl25sO2vkQ5C3hqb:-KXl85d__J16CXoMh3tV:b-896fix) ([raw file](https://github.com/uiri/trebletrouble/blob/3d03a58f7a905a2cda315975ee2220fa89475da9/Makefile#L35)):*
<details><summary><i>Previously, Ecobbold (Emilie Cobbold) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/app.c, line 24 at r1](https://reviewable.io:443/reviews/uiri/trebletrouble/61#-KXkiGDgeZrDVa-1WBoM:-KXl86hTpeKgaUxZwWcS:b-896fix) ([raw file](https://github.com/uiri/trebletrouble/blob/3d03a58f7a905a2cda315975ee2220fa89475da9/bbb/meta-bbb/recipes-core/trebletrouble/files/src/app.c#L24)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

lol typo `hbp` doesn't compile. Did you mean `fbp`
</blockquote></details>

Done.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/app.c, line 33 at r1](https://reviewable.io:443/reviews/uiri/trebletrouble/61#-KXkiQPAMfD8lAhReFbE:-KXl8E0l-qsZtuPd4ST0:b-896fix) ([raw file](https://github.com/uiri/trebletrouble/blob/3d03a58f7a905a2cda315975ee2220fa89475da9/bbb/meta-bbb/recipes-core/trebletrouble/files/src/app.c#L33)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

:question: TODO: Add useful display code
</blockquote></details>

Done.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 131 at r1](https://reviewable.io:443/reviews/uiri/trebletrouble/61#-KXkiulrwfLREzbPeLwZ:-KXl88GC8sLnShjzoBNs:b-896fix) ([raw file](https://github.com/uiri/trebletrouble/blob/3d03a58f7a905a2cda315975ee2220fa89475da9/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L131)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

FYI: clean up whitespace
</blockquote></details>

Done.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display_test.c, line 17 at r1](https://reviewable.io:443/reviews/uiri/trebletrouble/61#-KXkjg_4h8AsgXCqExMi:-KXl8F--rin297UCDulV:b-896fix) ([raw file](https://github.com/uiri/trebletrouble/blob/3d03a58f7a905a2cda315975ee2220fa89475da9/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display_test.c#L17)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

These should probably be `#define`'d as macros
</blockquote></details>

Done.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display_test.c, line 25 at r1](https://reviewable.io:443/reviews/uiri/trebletrouble/61#-KXkjvsJpl8hxeuwEXua:-KXl89DHLDucBrlETdgT:b-896fix) ([raw file](https://github.com/uiri/trebletrouble/blob/3d03a58f7a905a2cda315975ee2220fa89475da9/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display_test.c#L25)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

buf[3] only has 3 bytes... did you mean g -> buf[1], b -> buf[2] or did you mean to make buf 4 bytes wide?
</blockquote></details>

Done.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display_test.c, line 46 at r1](https://reviewable.io:443/reviews/uiri/trebletrouble/61#-KXkl1m9SrIBO3Bd7C0Q:-KXl8Ahhmnct065kJzEm:b-896fix) ([raw file](https://github.com/uiri/trebletrouble/blob/3d03a58f7a905a2cda315975ee2220fa89475da9/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display_test.c#L46)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

Please take out the debug code
</blockquote></details>

Done.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display_test.c, line 63 at r1](https://reviewable.io:443/reviews/uiri/trebletrouble/61#-KXklh9xcSHx0gKS1-DJ:-KXl8BICGQVbyCuXU7ta:b-896fix) ([raw file](https://github.com/uiri/trebletrouble/blob/3d03a58f7a905a2cda315975ee2220fa89475da9/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display_test.c#L63)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

Should this debug print statement be removed?
</blockquote></details>

Done.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display_test.c, line 66 at r1](https://reviewable.io:443/reviews/uiri/trebletrouble/61#-KXkm4PAE846hT_7loHB:-KXl8FnFTVKbRHjJLZQu:b-896fix) ([raw file](https://github.com/uiri/trebletrouble/blob/3d03a58f7a905a2cda315975ee2220fa89475da9/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display_test.c#L66)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

BTW you might want to add a comment to explain 105 (distance between same note in different octaves) and 15 ( distance between different notes)
</blockquote></details>

Done.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display_test.c, line 109 at r1](https://reviewable.io:443/reviews/uiri/trebletrouble/61#-KXknJrBh6ktdhEQ2apA:-KXl8CC3yPSIm6FF4QzV:b-896fix) ([raw file](https://github.com/uiri/trebletrouble/blob/3d03a58f7a905a2cda315975ee2220fa89475da9/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display_test.c#L109)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

FYI: neat trick you can do `for (i = 0; i < 5; i++, y += m)` 
</blockquote></details>

Done.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display_test.c, line 115 at r1](https://reviewable.io:443/reviews/uiri/trebletrouble/61#-KXknpYUWT8QIDq8Tu3l:-KXl8Cbv3bvU4dHrxSQj:b-896fix) ([raw file](https://github.com/uiri/trebletrouble/blob/3d03a58f7a905a2cda315975ee2220fa89475da9/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display_test.c#L115)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

This should end up in `display.c` so we can load a song onto the display on the board, no?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/uiri/trebletrouble/61)*

**Comment by uiri** [comment]
LGTM couple nits below.

---

Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 176 at r2](https://reviewable.io:443/reviews/uiri/trebletrouble/61#-KXlA3XgqQU3A5jr7_O7:-KXlA3XhmUEnm4BqtiQ2:b-nbp3fs) ([raw file](https://github.com/uiri/trebletrouble/blob/0b370d943f77c170c760e8addd7c8c99c240eab2/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L176)):*
> ```C
> 	/* place staff (five lines) on screen */
> 	int i;
> 	int x = 0;  
> ```

Is that trailing whitespace at the end of this line..?

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 194 at r2](https://reviewable.io:443/reviews/uiri/trebletrouble/61#-KXlAE0K0EFXM5RjnA3Y:-KXlAE0LL2OnuL1QCt8o:bm3kvoo) ([raw file](https://github.com/uiri/trebletrouble/blob/0b370d943f77c170c760e8addd7c8c99c240eab2/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L194)):*
> ```C
> 
> void load_song(FILE *song, char *fbp){
> 	/*TODO: return expected file?*/
> ```

return expected notes (ie: int*) not a file

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/uiri/trebletrouble/61#-:-KXlBkT1NlhkL302m9vL:b-39faqe)*

**Comment by Ecobbold** [comment]
picked all the nits.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/uiri/trebletrouble/61#-:-KXlCnRva8P-ofJVmq5k:bqc9t7)*

**Comment by uiri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/uiri/trebletrouble/61#-:-KXlDYdJfjLUOkU3h7gF:bnfp4nl)*

**Pull request merged**
